import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";

export default function index() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [school, setSchool] = useState("");

  const [error, setError] = useState(null);

  const [name, setName] = useState("");
  const [surname, setSurname] = useState("");

  const handleRegisterForm = async (e) => {
    e.preventDefault();
    const response = await axios.post(`${API_URL}`, {
      username: email,
      email: email,
      confirmed: true,
      password: password,
    });
    console.log(response.data);
  };

  return (
    <section className="auth-grid">
      <div className="yellow-grid"></div>
      <div
        style={{ display: "flex", flexDirection: "column" }}
        className="form__login-container"
      >
        <p className="p bold align-left">BuddyGram</p>
        <h1 className="h1 align-left">
          <marker
            style={{ backgroundColor: "var(--yellow)", color: "var(--black)" }}
          >
            Login
          </marker>{" "}
          als leerkracht
        </h1>
        <form
          style={{ gridTemplateColumns: "1fr", maxWidth: "40rem" }}
          onSubmit={handleRegisterForm}
          className="form__login"
        >
          <Head>
            <title>Login Leerkracht - BuddyGram</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          {error !== null ? <p>An error occured</p> : ""}

          <div>
            <label
              className="label-text p-small pixelated-font bold"
              htmlFor="email"
            >
              Email:
            </label>
            <input
              onChange={(e) => setEmail(e.currentTarget.value)}
              type="email"
              name="email"
              id="email"
              value={email}
              placeholder="email@email.com"
              className="input-margin auth-input"
              style={{ minWidth: "40rem" }}
            />
          </div>

          <div>
            <label
              className="label-text p-small pixelated-font bold"
              htmlFor="wachtwoord"
            >
              Wachtwoord:
            </label>

            <input
              onChange={(e) => setPassword(e.currentTarget.value)}
              type="text"
              value={password}
              id="wachtwoord"
              name="wachtwoord"
              placeholder="Typ uw wachtwoord hier..."
              className="input-margin auth-input"
              style={{ minWidth: "40rem" }}
            />
          </div>

          <input
            className="form__auth--button button-primary-blue"
            value="inloggen"
            type="submit"
          />
        </form>
        <div className="form__login-alreadyRegistered flex-horizontal p-small auth-">
          <p>Nog geen account?</p>
          <Link href="/register">
            <span style={{ marginLeft: "0.5rem" }} className="bold blue">
              Registreer jezelf als leerkracht
            </span>
          </Link>
        </div>
      </div>
    </section>
  );
}
