import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";

export default function index() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(null);

  const handleRegisterForm = async (e) => {
    e.preventDefault();
    const response = await axios.post(`${API_URL}`, {
      username: email,
      email: email,
      confirmed: true,
      password: password,
    });
    console.log(response.data);
  };

  return (
    <div
      style={{ display: "flex", flexDirection: "column" }}
      className="form__login-container"
    >
      <h1 className="h1">Register</h1>
      <form onSubmit={handleRegisterForm} className="form__login">
        <Head>
          <title>Login Leerkracht - BuddyGram</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {error !== null ? <p>An error occured</p> : ""}
        <label className="label-text" htmlFor="email">
          Email
        </label>
        <input
          onChange={(e) => setEmail(e.currentTarget.value)}
          type="text"
          name="email"
          id="email"
          value={email}
          placeholder="email@email.com"
          className="input-margin"
        />

        <label className="label-text" htmlFor="password">
          Password
        </label>
        <input
          onChange={(e) => setPassword(e.currentTarget.value)}
          type="text"
          value={password}
          id="password"
          name="password"
          placeholder="Type password here"
          className="input-margin"
        />
        <input className="form__auth--button" type="submit" />
        <Link href="/register">Create an account</Link>
      </form>
    </div>
  );
}
