import React, { useState } from "react";
import Head from "next/head";
import axios from "axios";
import { API_URL } from "../../constants/index";

export default function index() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(null);

  const handleRegisterForm = async (e) => {
    e.preventDefault();
    const response = await axios.post(`${API_URL}`, {
      username: email,
      email: email,
      confirmed: true,
      password: password,
    });
    console.log(response.data);
  };

  return (
    <div className="form__register-container">
      <form className="form__register" onSubmit={handleRegisterForm}>
        <Head>
          <title>Registreren Leerkracht - BuddyGram</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {error !== null ? <p>An error occured</p> : ""}
        <label className="label-text" htmlFor="email">
          Email
        </label>
        <input
          onChange={(e) => setEmail(e.currentTarget.value)}
          type="text"
          name="email"
          id="email"
          value={email}
          placeholder="email@email.com"
          className="input-margin"
        />

        <label className="label-text" htmlFor="password">
          Password
        </label>
        <input
          onChange={(e) => setPassword(e.currentTarget.value)}
          type="text"
          value={password}
          id="password"
          name="password"
          placeholder="Type password here"
          className="input-margin"
        />

        <input className="form__auth--button" type="submit" />
      </form>
    </div>
  );
}
