import React, { useState } from "react";
import LoadingBar from "../../components/LoadingBar/LoadingBar";
import axios from "axios";
import ProfilePictureForm from "../../components/Forms/ProfilePictureForm";
import Head from "next/head";
import DragAndDrop from "../../components/Interactive/DragAndDrop";
import { useStoreState } from "easy-peasy";
import CustomCursor from "../../components/CustomCursor/CustomCursor";

import Introduction from "../../components/Introduction/Introduction";

import Onboarding1 from "../../components/Onboarding/Onboarding1";
import Onboarding2 from "../../components/Onboarding/Onboarding2";
import Onboarding3 from "../../components/Onboarding/Onboarding3";
import Onboarding4 from "../../components/Onboarding/Onboarding4";

import Dag1 from "../../components/Dag1/Dag1";


export default function Index({ data, ctx, succes, id }) {
  const routeId = useStoreState((state) => state.route);

  console.log(routeId);

  //Routes bepaald welke componenten er geladen worden

  /*
  const routes = [
    {
      id: 0,
      action: "Star van het spel",
      percent: 0,
      component: <Introduction setRoute={setRoute} />,
    },
    {
      id: 1,
      action: "Foto uploaden",
      percent: 30,
      component: <ProfilePictureForm setRoute={setRoute} />,
    },
    {
      id: 2,
      action: "Foto uploaden",
      percent: 30,
      component: <DragAndDrop setRoute={setRoute} />,
    },
  ];
  */

  const routes = [
    {
      id: 0,
      name: "Introductie",
      component: <Introduction title={"Introductie"} />,
    },
    {
      id: 1,
      name: "Stap 1",
      component: <Onboarding1 title={"Stap 1"} />,
    },
    {
      id: 2,
      name: "Stap 2",
      component: <Onboarding2 title={"Stap 2"} />,
    },
    {
      id: 3,
      name: "Stap 3",
      component: <Onboarding3 title={"Stap 3"} />,
    },
    {
      id: 4,
      name: "Stap 4",
      component: <Onboarding4 title={"Stap 4"} />,
    },
    {
      id: 5,
      name: "Dag 1",
      component: <Dag1 title={"Dag 1"} />,
    },
  ];

  return (
    <>
      <Head>
        <title>{routes[routeId].name} - BuddyGram</title>
        <link rel="icon" href="/smiley.png" />
      </Head>
      <CustomCursor />
      {routes[routeId].component}
    </>
  );
}

/*
return (
    <section className="exercise-form-start">
      <Head>
        <title>Game - BuddyGram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {routes[route].component}
      <LoadingBar
        action={routes[route].action}
        percent={routes[route].percent}
      />
    </section>
  );
*/

export async function getServerSideProps(context) {
  const { id } = context.params;
  //Code that checks if game actually exists

  const response = await axios.get(
    `http://localhost:1337/links/?link_id=${id}`
  );
  console.log(response.data);
  if (response?.data?.length === 1) {
    console.log("Found a game");
    return {
      props: {
        success: true,
        id: id,
      },
    };
  }

  return {
    redirect: {
      destination: "/",
      permanent: false,
    },
  };
}
