import React, { useState } from "react";
import LayoutTeacher from "../../components/Layout/LayoutTeacher";
import { v4 as uuid } from "uuid";
import axios from "axios";
import Head from "next/head";
import CustomCursor from "../../components/CustomCursor/CustomCursor";
import { getSession, useSession } from "next-auth/client";

import ChangeStudents from "../../components/Dashboard/ChangeStudents";
import Game from "../../components/Dashboard/ChangeStudents";
import Games from "../../components/Dashboard/ChangeStudents";
import NewGame from "../../components/Dashboard/ChangeStudents";
import Students from "../../components/Dashboard/ChangeStudents";
import NavDashboard from "../../components/Dashboard/NavDashboard";

export default function index() {
  const [link, setLink] = useState("");

  const [id, setId] = useState(0);

  const routes = [
    {
      id: 0,
      name: "Nieuwe game",
      component: <NewGame />,
    },
    {
      id: 1,
      name: "Gemaakte spellen",
      component: <Games />,
    },
    {
      id: 2,
      name: "Game pagina",
      component: <Game />,
    },
    {
      id: 3,
      name: "Nieuwe game",
      component: <NewGame />,
    },
    {
      id: 4,
      name: "Nieuwe game",
      component: <NewGame />,
    },
  ];

  const handleGenerateLink = (e) => {
    e.preventDefault();

    try {
      axios
        .post("http://localhost:1337/links", {
          link_id: uuid(),
          user_permissions_user: 0,
        })
        .then((response) => {
          console.log(response.data);
          setLink(`http://localhost:3000/game/${response?.data?.link_id}`);
        });
    } catch (e) {
      console.log("Error: " + e);
    }
  };

  return (
    <LayoutTeacher>
      <Head>
        <title>Leerkracht Dashboard - BuddyGram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="wrapper">
        <p className="label-text">
          Genereer een link en deel deze met je studenten
        </p>
        <form className="form__generateLink" onSubmit={handleGenerateLink}>
          <input
            type="text"
            value={link}
            onChange={(e) => setLink(e.currentTarget.value)}
            className="input__generatedlink"
            readOnly
          />
          <input type="submit" value="Generate link" />
        </form>
      </section>
    </LayoutTeacher>
  );
}

export async function getServerSideProps(ctx) {
  console.log(await getSession(ctx));

  return {
    props: {
      session: await getSession(ctx),
    },
  };
}
