import React, { useState } from "react";
import LayoutTeacher from "../../components/Layout/LayoutTeacher";
import { v4 as uuid } from "uuid";
import axios from "axios";
import Head from "next/head";
import CustomCursor from "../../components/CustomCursor/CustomCursor";
import { getSession, session, useSession } from "next-auth/client";

import ChangeStudents from "../../components/Dashboard/ChangeStudents";
import Game from "../../components/Dashboard/Game";
import Games from "../../components/Dashboard/Games";
import NewGame from "../../components/Dashboard/NewGame";
import Students from "../../components/Dashboard/Students";

import NavDashboard from "../../components/Dashboard/NavDashboard";

export default function index({ session }) {
  const teacher = session?.user?.user?.user.teacher;
  //console.log(session?.user?.user?.user.teacher);

  const [game, setGame] = useState(null);

  const [id, setId] = useState(0);

  const routes = [
    {
      id: 0,
      name: "Nieuwe game",
      component: <NewGame teacher={teacher} />,
    },
    {
      id: 1,
      name: "Gemaakte spellen",
      component: <Games setId={setId} setGame={setGame} teacher={teacher} />,
    },
    {
      id: 2,
      name: "Game pagina",
      component: <Game setId={setId} game={game} teacher={teacher} />,
    },
    {
      id: 3,
      name: "Nieuwe game",
      component: <NewGame />,
    },
    {
      id: 4,
      name: "Nieuwe game",
      component: <NewGame />,
    },
  ];

  return (
    <LayoutTeacher id={id} setId={setId}>
      <Head>
        <title>Leerkracht Dashboard - BuddyGram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/smiley.png" />
      </Head>
      <div>{routes[id].component}</div>
    </LayoutTeacher>
  );
}

export async function getServerSideProps(ctx) {
  return {
    props: {
      session: await getSession(ctx),
    },
  };
}
