import React, { useState } from "react";
import LayoutTeacher from "../../components/Layout/LayoutTeacher";
import { v4 as uuid } from "uuid";
import axios from "axios";
import Head from "next/head";
import CustomCursor from "../../components/CustomCursor/CustomCursor";
import { getSession, session, useSession } from "next-auth/client";

import ChangeStudents from "../../components/Dashboard/ChangeStudents";
import Game from "../../components/Dashboard/Game";
import Games from "../../components/Dashboard/Games";
import NewGame from "../../components/Dashboard/NewGame";
import Students from "../../components/Dashboard/Students";

import NavDashboard from "../../components/Dashboard/NavDashboard";

export default function index({ session }) {
  const teacher = session?.user?.user?.user.teacher;
  //console.log(session?.user?.user?.user.teacher);

  const [link, setLink] = useState("");

  const [id, setId] = useState(0);

  const routes = [
    {
      id: 0,
      name: "Nieuwe game",
      component: <NewGame />,
    },
    {
      id: 1,
      name: "Gemaakte spellen",
      component: <Games />,
    },
    {
      id: 2,
      name: "Game pagina",
      component: <Game />,
    },
    {
      id: 3,
      name: "Nieuwe game",
      component: <NewGame />,
    },
    {
      id: 4,
      name: "Nieuwe game",
      component: <NewGame />,
    },
  ];

  const handleGenerateLink = (e) => {
    e.preventDefault();

    try {
      axios
        .post("http://localhost:1337/links", {
          link_id: uuid(),
          user_permissions_user: 0,
        })
        .then((response) => {
          console.log(response.data);
          setLink(`http://localhost:3000/game/${response?.data?.link_id}`);
        });
    } catch (e) {
      console.log("Error: " + e);
    }
  };

  return (
    <LayoutTeacher>
      <Head>
        <title>Leerkracht Dashboard - BuddyGram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/smiley.png" />
      </Head>
      <div>
        <NewGame teacher={teacher} />
      </div>
    </LayoutTeacher>
  );
}

export async function getServerSideProps(ctx) {
  return {
    props: {
      session: await getSession(ctx),
    },
  };
}
