import Head from "next/head";
import Nav from "../components/Layout/Nav";
import CustomCursor from "../components/CustomCursor/CustomCursor";
import { useStoreState } from "easy-peasy";
import Image from "next/image";
import Link from "next/link";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";

export default function Home() {
  //DIT IS DE HOME PAGINA

  var settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    centerMode: true
  };

  return (
    <>
      <CustomCursor />
      
      <Head>
        <title>Home - BuddyGram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="/smiley.png" />
      </Head>
      
      <Nav/>

        <main className="home__container">
          <article className="header__container">
            <div className="header__content">
              <div className="header__box">

                <div className="image__love">
                  <Image
                    src="/assets/img/love.svg"
                    width={114}
                    height={102}
                    alt="Illustratie van een container"
                  />
                </div>
                
                <div className="header__intro box__shadow">
                  <h2 className="title__l-bold"><mark className="mark-red">wapen</mark> de nieuwe generatie tegen cyberpesten</h2>
                  <div className="spacer__s"></div>
                  <p className="text__m-normal text__with">Een beleving vol valstrikken die zich schuilen in de social media van tegenwoordig.</p>
                </div>
                
                <div className="buttons__container">

                  <a href="#about__working" className="button__secondary button__secondary-home">hoe werkt het?</a>

                  <Link href="/login">
                    <span className="button__primary button__primary-home">start het spel</span>
                  </Link>

                </div>

              </div>
                
                <div className="header__img">
                  <Image
                    src="/assets/img/header_illu.svg"
                    width={456}
                    height={438}
                    alt="Illustratie van een container"
                  />
                </div>

                <div className="image__grid">
                  <Image
                    src="/assets/img/headerGrid.svg"
                    width={594}
                    height={528}
                    alt="Illustratie van een container"
                  />
                </div>

                <div className="image__arrowDown">
                  <Image
                    src="/assets/img/arrowDown.svg"
                    width={30}
                    height={51}
                    alt="pijltje naar onder"
                  />
                </div>
              
            </div>

            <div className="marquee__container">
              <div className="marquee__scrolling title__s-bold">“Wat een lelijke foto!” - “Hé, vuurtoren!” - “Je posts boeien niemand.” - “De mooie foto’s waren op zeker?” - “Met zo’n neus kan je een brood snijden!” -</div>
              <div className="marquee__scrolling title__s-bold" aria-hidden="true">“Wat een lelijke foto!” - “Hé, vuurtoren!” - “Je posts boeien niemand.” - “De mooie foto’s waren op zeker?” - “Met zo’n neus kan je een brood snijden!” -</div>
            </div>

          </article>
          
          <div className="info__container-1">
            
            <article className="info__container-left" id="about__working">
              <span className="text__m-bold text__blue">Hoe werkt het?</span>
              <div className="spacer__s"></div>
              <h2 className="title__m-bold">Leer jongeren omgaan met verschillende online situaties met deze <mark className="mark-blue">interactieve</mark> beleving.</h2>
              <div className="spacer__s"></div>
              <p className="text__m-normal text__with">De 13 tot 15 jarigen gaan met verschillende scenario’s aan de slag om zo de negatieve kant van social media te leren kennen.</p>
            </article>

            <div className="image__pill-red">
              <Image
                src="/assets/img/pillRed.svg"
                width={60}
                height={180}
                alt="rood designelement"
              />
            </div>

            <div className="image__plus-yellow">
              <Image
                src="/assets/img/plusYellow.svg"
                width={80}
                height={80}
                alt="geel designelement"
              />
            </div>

            <div className="image__lightning">
              <Image
                src="/assets/img/lightning.svg"
                width={312}
                height={562}
                alt="bliksem stroke afbeelding"
              />
            </div>

          </div>
            
          <div className="lightningDevider__container">
            <img
              src="/assets/img/lightningDevider.svg"
              alt="bliksem stroke afbeelding"
              className="lightningDevider"
            />
          </div>

          <div className="image__donut-red">
              <Image
                src="/assets/img/donutRed.svg"
                width={110}
                height={110}
                alt="geel designelement"
              />
          </div>
            
          <div className="info__wrapper-blue">
            
            <div className="info__container-2">
              
              <article className="info__container-center">
                <span className="text__m-bold text__white">De gevolgen van cyberpesten</span>
                <div className="spacer__s"></div>
                <h2 className="title__m-bold text__white">"Hoe <mark className="mark-turquoise">10</mark> minuten op instagram mijn dag verpestte.”</h2>
                <div className="spacer__s"></div>
                <p className="text__m-normal text__white">Katrien, 13 jaar</p>
              </article>

              <div className="image__pill-yellow">
                <Image
                  src="/assets/img/pillYellow.svg"
                  width={60}
                  height={160}
                  alt="geel designelement"
                />
              </div>

            </div>

          </div>

          <div className="info__wrapper-yellow">

            <div className="info__container-3">

              <div className="car__container box__shadow">
                
                <div className="car__top">
                  
                  <p className="title__s-bold">stappen tot succes</p>
                  
                  <div className="car__cross">
                    <Image
                      src="/assets/img/crossBlack.svg"
                      width={25}
                      height={25}
                      alt="kruisje om kader af te sluiten"
                    />
                  </div>
                </div>

                <div className="car__info">
                  <Slider {...settings}>
                    <div className="car__info-wrapper">
                      <span className="text__m-bold text__blue">stap 1:</span>
                      <h2 className="title__m-bold"><mark className="mark-blue">registreer</mark> je als leerkracht</h2>
                      <div className="spacer__s"></div>
                      <p className="text__m-normal car__info-text">Maak een account aan als leerkracht en krijg toegang tot het paneel.</p>
                    </div>
                    <div className="car__info-wrapper">
                      <span className="text__m-bold text__blue">stap 2:</span>
                      <h2 className="title__m-bold">maak een <mark className="mark-blue">spel</mark>aan</h2>
                      <div className="spacer__s"></div>
                      <p className="text__m-normal car__info-text">Druk op "nieuw spel" in het dashboard en ga naar de volgende stap.</p>
                    </div>
                    <div className="car__info-wrapper">
                      <span className="text__m-bold text__blue">stap 3:</span>
                      <h2 className="title__m-bold"><mark className="mark-blue">leerlingen</mark> toevoegen</h2>
                      <div className="spacer__s"></div>
                      <p className="text__m-normal car__info-text">Voeg al jouw leerlingen toe aan het spel.</p>
                    </div>
                    <div className="car__info-wrapper">
                      <span className="text__m-bold text__blue">stap 4:</span>
                      <h2 className="title__m-bold"><mark className="mark-blue">genereer</mark> een link</h2>
                      <div className="spacer__s"></div>
                      <p className="text__m-normal car__info-text">Stuur deze link door naar de toestellen.</p>
                    </div>
                    <div className="car__info-wrapper">
                      <span className="text__m-bold text__blue">stap 5:</span>
                      <h2 className="title__m-bold"><mark className="mark-blue">monitor</mark>de resultaten</h2>
                      <div className="spacer__s"></div>
                      <p className="text__m-normal car__info-text">Achterna zie je de resultaten in het dashboard.</p>
                    </div>
                  </Slider>
                </div>
              </div>

              <div className="image__gridYellow">
                <img
                  src="/assets/img/gridYellow.svg"
                  width={528}
                  height={671}
                  alt="grid illustratie"
                />
              </div>
              
              <div className="spacer__l"></div>

              <article className="info__container-left">
                <span className="text__m-bold text__blue">Volle controle</span>
                <div className="spacer__s"></div>
                <h2 className="title__m-bold">Als <mark className="mark-blue">leerkracht</mark> heb je zicht op hoe de leerlingen presteren.</h2>
                <div className="spacer__s"></div>
                <p className="text__m-normal text__with">Via het leerkrachtenpaneel kan je ‘Buddy or Bully’ opstarten en delen met je studenten. Daarnaast heb je ook zicht op de resultaten van de studenten en kan je de focus van de lessen leggen waar nodig.</p>
              </article>

              <div className="spacer__m"></div>

              <div className="buttons__container">
                <Link href="/login">
                  <span className="button__primary">login als leerkracht</span>
                </Link>
              </div>

            </div>

            <div className="image__thumb">
              <Image
                src="/assets/img/thumb.svg"
                width={155}
                height={155}
                alt="duimpje naar onder afbeelding"
              />
            </div>

            <div className="image__blocksYellow">
              <Image
                src="/assets/img/blocksYellow.svg"
                width={500}
                height={300}
                alt="gele blokjes illustratie"
              />
            </div>

          </div>

          <div className="info__wrapper-white">

            <div className="info__container-4">

              <article className="info__container-center">
                <span className="text__m-bold text__red">De kracht van reflectie</span>
                <div className="spacer__s"></div>
                <h2 className="title__m-bold">Neem vervolgens de kans om er met de leerlingen <mark className="mark-red2">openhartig</mark> over te spreken</h2>
              </article>

            </div>

            <div className="image__pixelatedHeads">
                <Image
                  src="/assets/img/pixelatedHeads.png"
                  width={620}
                  height={420}
                  alt="foto waarbij hoofden onkenbaar zijn"
                />
              </div>

          </div>

          <div className="lightningDevider__container">
            <img
              src="/assets/img/lightningDevider.svg"
              alt="bliksem stroke afbeelding"
              className="lightningDevider"
            />
          </div>

          <div className="image__donut-red">
              <Image
                src="/assets/img/donutRed.svg"
                width={110}
                height={110}
                alt="geel designelement"
              />
          </div>

          <div className="info__wrapper-blue">
            
            <div className="info__container-5">

              <article className="info__container-center">
                <h2 className="title__l-bold text__white">"Buddy or Bully is <mark className="mark-yellow2">helemaal</mark> gratis</h2>
                <div className="spacer__s"></div>
                <p className="text__m-normal text__white">Als school en leerkracht hoef je niets te betalen. Je krijgt meteen toegang tot een dashboard waarop je als leerkracht het spel kan opstarten voor de studenten.</p>
                <div className="spacer__m"></div>
              </article>

              <div className="buttons__container-center">
                <Link href="/register">
                  <span className="button__primary">start nu gratis</span>
                </Link>
              </div>

              <div className="image__pill-yellow">
                <Image
                  src="/assets/img/pillYellow.svg"
                  width={60}
                  height={160}
                  alt="geel designelement"
                />
              </div>

              <div className="image__plus-red">
                <Image
                  src="/assets/img/plusRed.svg"
                  width={80}
                  height={80}
                  alt="geel designelement"
                />
              </div>

              <div className="image__gridBlue">
                <img
                  src="/assets/img/gridBlue.svg"
                  width={528}
                  height={671}
                  alt="grid illustratie"
                />
              </div>

            </div>
          </div>
        </main>

        <footer className="footer__container">
          
          <div className="footer__wrapper">
            <p className="title__m-bold text__white">integration 4</p>
            <p className="title__m-bold text__white">devine</p>
          </div>

        </footer>
      
    </>
  );
}
