import Head from "next/head";
import Nav from "../components/Layout/Nav";
import CustomCursor from "../components/CustomCursor/CustomCursor";
import { useStoreState } from "easy-peasy";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  //DIT IS DE HOME PAGINA

  return (
    <>
      <CustomCursor />
      
      <Head>
        <title>Home - BuddyGram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/smiley.png" />
      </Head>
      
      <Nav/>

        <main className="home__container">
          <article className="header__container">
            <div className="header__content">
              <div className="header__box">
                
                <div className="header__intro box__shadow">
                  <h2 className="title__l-bold"><mark className="mark-red">wapen</mark> de nieuwe generatie tegen cyberpesten</h2>
                  <div className="spacer__s"></div>
                  <p className="text__m-normal text__with">Een beleving vol valstrikken die zich schuilen in de social media van tegenwoordig.</p>
                </div>
                
                <div className="buttons__container">
                  <Link href="/register">
                    <span className="button__secondary">hoe werkt het?</span>
                  </Link>
                  <Link href="/register">
                  <span className="button__primary">start het spel</span>
                  </Link>
                </div>

              </div>
                
                <div className="header__img">
                  <Image
                    src="/assets/img/header_illu.svg"
                    width={456}
                    height={438}
                    alt="Illustratie van een container"
                  />
                </div>

                <div className="image__grid">
                  <Image
                    src="/assets/img/headerGrid.svg"
                    width={594}
                    height={528}
                    alt="Illustratie van een container"
                  />
                </div>

                <div className="image__arrowDown">
                  <Image
                    src="/assets/img/arrowDown.svg"
                    width={30}
                    height={51}
                    alt="pijltje naar onder"
                  />
                </div>

              
            </div>

            <div className="marquee__container">
              <div className="marquee__scrolling title__s-bold">“Wat een lelijke foto!” - “Hé, vuurtoren!” - “Je posts boeien niemand.” - “De mooie foto’s waren op zeker?” - “Met zo’n neus kan je een brood snijden!” -</div>
              <div className="marquee__scrolling title__s-bold" aria-hidden="true">“Wat een lelijke foto!” - “Hé, vuurtoren!” - “Je posts boeien niemand.” - “De mooie foto’s waren op zeker?” - “Met zo’n neus kan je een brood snijden!” -</div>
            </div>

          </article>
          
          <div className="info__container-1">
            
            <article className="info__container-left">
              <span className="text__m-bold text__blue">Hoe werkt het?</span>
              <h2 className="title__m-bold">Leer jongeren omgaan met verschillende online situaties met deze <mark className="mark-blue">interactieve</mark> beleving.</h2>
              <div className="spacer__s"></div>
              <p className="text__m-normal text__with">De 13 tot 15 jarigen gaan met verschillende scenario’s aan de slag om zo de negatieve kant van social media te leren kennen.</p>
            </article>

            <div className="image__lightning">
              <Image
                src="/assets/img/lightning.svg"
                width={312}
                height={562}
                alt="bliksem stroke afbeelding"
              />
            </div>

          </div>
            
          <div className="lightningDevider__container">
            <img
              src="/assets/img/lightningDevider.svg"
              alt="bliksem stroke afbeelding"
              className="lightningDevider"
            />
          </div>
            
          <div className="info__wrapper-blue">
            
            <div className="info__container-2">

            </div>

          </div>

          <div className="info__wrapper-yellow">
            
            <div className="info__container-3">

            </div>

          </div>

          <div className="info__wrapper-white">

            <div className="info__container-4">

            </div>

          </div>

          <div className="lightningDevider__container">
            <img
              src="/assets/img/lightningDevider.svg"
              alt="bliksem stroke afbeelding"
              className="lightningDevider"
            />
          </div>

          <div className="info__wrapper-blue">
            
            <div className="info__container-5">

            </div>

          </div>
        </main>
        
        
        
        
        
        
        
        
        
        {/* <main className={styles.main}>
          <section className="header__home">
            <div style={{ position: "relative" }} className="wrapper">
              <div className="header__whiteBox-container">
                <div className="header__whiteBox-outside">
                  <div className="header__whiteBox-inside">
                    <h1 className="h1">
                      Wapen de nieuwe generatie tegen cyberpesten
                    </h1>
                    <p>
                      Leer jongeren omgaan met verschillende online situaties
                      dankzij deze interactieve beleving!
                    </p>
                  </div>
                </div>
              </div>
              <div className="header__image-container">
                <Image
                  src="/assets/img/header_illu.svg"
                  width={456}
                  height={438}
                  alt="Illustratie van een container"
                />
              </div>
            </div>
          </section>
          <div className="black-bar-infinite">
            <Marquee />
          </div>
        </main> */}
      
    </>
  );
}
